//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace momoWear.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tcategory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tcategory()
        {
            this.tclothes = new HashSet<tclothes>();
        }
    
        public int fid { get; set; }
        public string fcategoryID { get; set; }
        public string fcategoryName { get; set; }
        public Nullable<System.DateTime> fmodifiedDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tclothes> tclothes { get; set; }
    }
}
