//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace momoWear.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web;

    public partial class tclothes
    {
        public int? fid { get; set; }
        public string fserialNumber { get; set; }
        public Nullable<int> fcategoryID { get; set; }
        public string fname { get; set; }
        public string fcolor { get; set; }
        public string fsize { get; set; }
        public Nullable<int> fquentity { get; set; }
        public string fdescribe { get; set; }
        public Nullable<int> fsalesVolume { get; set; }
        public Nullable<decimal> fprice { get; set; }
        public Nullable<System.DateTime> fsalesdate { get; set; }
        public Nullable<short> fsafetyStockLevel { get; set; }
        public Nullable<System.DateTime> fmodifiedDate { get; set; }
        public string fbrand { get; set; }
        public string fphotoPath { get; set; }
    
        public virtual tcategory tcategory { get; set; }

        public HttpPostedFileBase photo { get; set; }
    }
}
