//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace momoWear.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tcustomer
    {
        public int fid { get; set; }
        public string foutId { get; set; }
        public string fcustomerName { get; set; }
        public string fcustomerPhone { get; set; }
        public string faddress { get; set; }
        public Nullable<System.DateTime> fcustomerBirth { get; set; }
        public string flineAcc { get; set; }
        public string fstatus { get; set; }
        public string note { get; set; }
        public string ffacebookId { get; set; }
        public Nullable<System.DateTime> fAddtime { get; set; }
        public Nullable<System.DateTime> fmodifytime { get; set; }
    }
}
